### PR TITLE
Merge frontend and backend login

### PR DESCRIPTION
**Pull request by rgregers**
Merge login page from Boone and login post method from Ryan

### CODE REVIEW

**Comment by rgregers** [comment]
Merge login page from Boone and login post method from Ryan

**Review by boone-p — APPROVED** [review]
looks good, i also have a validate login method in the user schema, which one do you want to use?

**Comment by rgregers** [comment]
I ended up using the schema that I created!

**Comment by Justin5iu** [comment]
looks good to me

**Review by ryandmaier — COMMENTED** [review]
Looks good, sounds like it works

**Pull request merged**
