### PR TITLE
Booneregistration

### PR DESCRIPTION
**Pull request by boone-p**

### CODE REVIEW

**Comment by rgregers** [comment]
Looks good to me! Nice work on the image upload

**Comment by boone-p** [comment]
Sweet! Thanks ryan!

**Comment by Justin5iu** [comment]
Great work!

**Review by ryandmaier — COMMENTED** [review]
What is getProductsLanding() for?

**Comment by boone-p** [comment]
> 

Thanks Justin!

**Comment by boone-p** [comment]
getProductsLanding() just gets all the current products in the Products Collection and sends its to the backend for it to display on our frontend Landing page.

**Pull request merged**
